import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Olga',
      email: 'olha.kuriatnyk@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Alex',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: '1',
      name: 'Glass Water Bottle',
      category: 'Glass Bottle',
      image: '/images/p1.jpg',
      price: 30,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'This bottle has round glass body, silicon cover, and wooden cap, it smoothly adapts to any enviroment.',
    },
    {
      _id: '2',
      name: 'Glass Water Bottle',
      category: 'Glass Bottle',
      image: '/images/p2.jpg',
      price: 30,
      countInStock: 12,
      rating: 4.0,
      numReviews: 12,
      description: 'This bottle has round glass body, silicon cover, and wooden cap, it smoothly adapts to any enviroment.',
    },
    {
      _id: '3',
      name: 'Stainless Steel Water Bottle',
      category: 'Stainless Steel Bottle',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 0,
      rating: 5,
      numReviews: 1,
      description: 'This bottle has stainless-steel structure makes it sufficiently strong to endure your frantic everyday life, with a beautiful, current design.',
    },
    {
      _id: '4',
      name: 'Glass Water Bottle',
      category: 'Glass Bottle',
      image: '/images/p4.jpg',
      price: 30,
      countInStock: 15,
      rating: 5,
      numReviews: 2,
      description: 'This bottle has round glass body, and wooden cap, it smoothly adapts to any enviroment.',
    },
    {
      _id: '5',
      name: 'Stainless Steel Water Bottle',
      category: 'Stainless Steel Bottle',
      image: '/images/p5.jpg',
      price: 35,
      countInStock: 5,
      rating: 4.8,
      numReviews: 25,
      description: 'This stainless steel bottle tructure makes it sufficiently strong to endure your frantic everyday life, with a beautiful, current design. ',
    },
    {
      _id: '6',
      name: 'Tritan Water Bottle',
      category: 'Tritan Bottle',
      image: '/images/p6.jpg',
      price: 15,
      countInStock: 12,
      rating: 0,
      numReviews: 0,
      description: 'This bottle has an exclusive magnet opening, which will allow you to be refreshed more quickly and easily, so you can enjoy your favourite sport without losing your personal style.',
    },
  ],
}
export default data;